export const prototypeLabs = [
  {
    id: 1,
    name: "Web Application Exploitation Lab",
    description:
      "Practice recon, authentication bypass, and input validation attacks against a purpose-built vulnerable web stack.",
    category: "Web Security",
    difficulty: "beginner",
    pricePerHour: 299,
    maxHours: 6,
    tools: ["Burp Suite", "OWASP ZAP", "cURL", "ffuf", "Firefox DevTools"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: 2,
    name: "Network Traffic Analysis Lab",
    description:
      "Investigate packet captures, suspicious flows, and credential leakage across a segmented network intrusion scenario.",
    category: "Network Forensics",
    difficulty: "intermediate",
    pricePerHour: 349,
    maxHours: 8,
    tools: ["Wireshark", "tcpdump", "Zeek", "tshark", "CyberChef"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: 3,
    name: "Malware Analysis Sandbox",
    description:
      "Dissect suspicious binaries, extract indicators, and study evasive behavior inside an isolated reverse-engineering environment.",
    category: "Malware Research",
    difficulty: "advanced",
    pricePerHour: 499,
    maxHours: 10,
    tools: ["Ghidra", "strings", "YARA", "PEStudio", "x64dbg"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: 4,
    name: "Linux Privilege Escalation Lab",
    description:
      "Hunt for sudo, SUID, and scheduled-task weaknesses to move from limited access to root in realistic Linux targets.",
    category: "Privilege Escalation",
    difficulty: "advanced",
    pricePerHour: 399,
    maxHours: 8,
    tools: ["LinPEAS", "GTFOBins", "pspy", "sudo", "bash"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: 5,
    name: "Active Directory Attack Range",
    description:
      "Enumerate a Windows domain, identify attack paths, and simulate Kerberos abuse against a small enterprise forest.",
    category: "Active Directory",
    difficulty: "advanced",
    pricePerHour: 599,
    maxHours: 12,
    tools: ["BloodHound", "Impacket", "Rubeus", "Mimikatz", "CrackMapExec"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: 6,
    name: "CTF Foundations Arena",
    description:
      "Build core capture-the-flag instincts with guided challenges across crypto, pwn, web, and forensic problem-solving.",
    category: "CTF Training",
    difficulty: "beginner",
    pricePerHour: 199,
    maxHours: 5,
    tools: ["Ghidra", "binwalk", "CyberChef", "pwndbg", "Wireshark"],
    imageUrl: null,
    isActive: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
] as const;
